// product/playbook/embed-book.mjs — GENERATES lib/book-pdf.ts and
// lib/companion-zip.ts from the compiled book + companion archive, the
// same trick as embed-ch1.mjs: base64 in a TS module so the webhook
// route can attach both without filesystem tracing config.
//
// Run from repo root after ANY book recompile or companion change:
//   node product/playbook/embed-book.mjs
import { readFileSync, writeFileSync } from "node:fs";

const jobs = [
  {
    src: "product/playbook/output/the-80-percent-wall.pdf",
    out: "lib/book-pdf.ts",
    constName: "BOOK_PDF_BASE64",
    fileConst: "BOOK_FILENAME",
    filename: "the-80-percent-wall.pdf",
  },
  {
    src: "product/playbook/output/the-80-percent-wall-companion.zip",
    out: "lib/companion-zip.ts",
    constName: "COMPANION_ZIP_BASE64",
    fileConst: "COMPANION_FILENAME",
    filename: "the-80-percent-wall-companion.zip",
  },
];

for (const j of jobs) {
  const bytes = readFileSync(j.src);
  const b64 = bytes.toString("base64");
  const body = [
    `// ${j.out} — GENERATED by product/playbook/embed-book.mjs.`,
    "// Base64 of a purchase deliverable, embedded so the Stripe webhook",
    "// route can attach it without filesystem tracing config. Do not",
    "// edit by hand; rebuild the artifact and re-run the script.",
    `export const ${j.constName} = "${b64}";`,
    `export const ${j.fileConst} = "${j.filename}";`,
    "",
  ].join("\n");
  writeFileSync(j.out, body);
  console.log(`embedded ${bytes.length} bytes -> ${b64.length} chars (${j.out})`);
}
