// Regenerates lib/chapter1-pdf.ts from the compiled PDF. Run after
// every chapter-01 recompile so the served copy never drifts:
//   node product/playbook/embed-ch1.mjs
import { readFileSync, writeFileSync } from "node:fs";
const pdf = readFileSync("product/playbook/output/the-80-percent-wall-ch1.pdf");
const b64 = pdf.toString("base64");
writeFileSync(
  "lib/chapter1-pdf.ts",
  [
    "// lib/chapter1-pdf.ts — GENERATED by product/playbook/embed-ch1.mjs.",
    "// Base64 of the compiled Chapter 1 PDF, embedded so the server",
    "// action can attach it without filesystem tracing config. Do not",
    "// edit by hand; recompile the chapter and re-run the script.",
    `export const CHAPTER1_PDF_BASE64 = "${b64}";`,
    `export const CHAPTER1_FILENAME = "the-80-percent-wall-ch1.pdf";`,
    "",
  ].join("\n"),
);
console.log("embedded", pdf.length, "bytes ->", b64.length, "chars");
